name: Build, Test & Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-node-app .

      - name: Save Docker image
        run: docker save my-node-app | gzip > my-node-app.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-node-app-image
          path: my-node-app.tar.gz

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: my-node-app-image

      - name: Load Docker image
        run: gunzip -c my-node-app.tar.gz | docker load

      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name my-node-app my-node-app

      - name: Wait for container to start
        run: sleep 10  # Attendre que l'application démarre

      - name: Test if API is running
        run: curl --fail http://localhost:8080/ || (docker logs my-node-app && exit 1)

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: my-node-app-image

      - name: Load Docker image
        run: gunzip -c my-node-app.tar.gz | docker load

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push Docker image
        run: |
          docker tag my-node-app ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest
